### ISSUE TITLE
/seed/{seed}/info returns same image regardless of seed

### ISSUE THREAD

**Issue by mootari** [DMarby/picsum-photos#104]
The route `/seed/{seed}/info` always returns the same info. A few examples:
- https://picsum.photos/seed/picsum/info
- https://picsum.photos/seed/foo/info
- https://picsum.photos/seed/bar12/info

In all cases the (formatted) response is:
~~~json
{
    "id": "989",
    "author": "Paul Jarvis",
    "width": 4896,
    "height": 3264,
    "url": "https://unsplash.com/photos/eBDdgbM5dSo",
    "download_url": "https://picsum.photos/id/989/4896/3264"
}
~~~

**Comment by DMarby** [comment]
Hi @mootari,

Thank you for reporting this, the fix has been deployed now.
It seems like it is was indeed broken from the start, and the test was not able to catch it since it doesn't encompass multiple seeds, I'll look into expanding it in the future.

**Comment by mootari** [comment]
Works beautifully - thank you for the fix and the quick response!
