### ISSUE TITLE
New Feature Request: API to be able to search by tags on images 

### ISSUE THREAD

**Issue by ishaan812** [DMarby/picsum-photos#119]
Hey, avid user of lorem picsum since years. Always wanted this feature:
- Where each image we can automatically generate tags for. (use a visual llm to do so easily) 
- Search API to get only the images based on the tags /?search=['dogs']

Theres a lot more ideas too for me. Is there a roadmap for this service? Would you guys be open to contributions?

**Comment by DMarby** [comment]
Hi,

Thank you for opening an issue, we are not currently planning to support any kind of search/tagging.
In general, Lorem Picsum is in maintenance mode, we'll keep the service running indefinitely, but no current plans to extend the functionality or accepting contributions doing so.
