### ISSUE TITLE
Request: by hash

### ISSUE THREAD

**Issue by rstacruz** [DMarby/picsum-photos#12]
It'd be nice to have an image by hash. Frequently the use case is something like this:

``` erb
<% @movies.each do |movie| %>
  <img src="http://unsplash.it/200/200">
  <h3><%= movie.name %></h3>
<% end %>
```

This will have different the same unsplash image each time. You can use `?random`, but that'd make it change every page load and isn't cacheable.

``` erb
<% @movies.each do |movie| %>
  <img src="http://unsplash.it/200/200?hash=<%= movie.name.parameterize %>">
  <h3>Movie name</h3>
<% end %>
```

That way, it'd load from `http://unsplash.it/200/200/?hash=star-wars-force-awakens` — and unsplash.it can just pick an image based on that given string, which will always be the same even across page loads, and the list will have different images for each item.

**Comment by joachimlundberg** [comment]
:+1: 
I agree it would be nice to be able to filter by a keyword.

just like when you search on https://unsplash.com/search?utf8=✓&keyword=food

**Comment by DMarby** [comment]
Super overdue response to this, sorry about that.
This sounds like a great idea, will try to bring this feature into the currently ongoing rewrite 👍

**Comment by DMarby** [comment]
This has now been added, you can use the new `/seed/{seed}/{width}/{height}` endpoint.
More information about how to use it can be found on https://picsum.photos
