### ISSUE TITLE
Add blur amount

### ISSUE THREAD

**Issue by ryanirilli** [DMarby/picsum-photos#14]
first of all thank you guys for making this, it's a great tool to build beautiful screens.

I was wondering if you could add blur amount support, something like:

`https://unsplash.it/200/300/?blur=5px`

When I have some time I can check out the code and see about submitting a PR, but just thought I'd ask.

**Comment by davemuir** [comment]
1+ on this, blur is kind of extreme.
Text option would also be great like placehold.it

**Comment by DMarby** [comment]
I'll need to see how this scales, but will try to add it during the rewrite currently being done 👍

**Comment by DMarby** [comment]
This has now been added: You can specify a blur amount between 1 and 10 to adjust the amount, eg `https://picsum.photos/200?blur=2`
