### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by lesliecdubs** [DMarby/picsum-photos#18]
Love using these Unsplash It placeholders, but the site has been going down a lot and creating broken images on my dev sites.

Any updates on stability? I'll have to switch placeholder providers if this continues.

**Comment by redaxmedia** [comment]
I suggest to ask the community for one or two mirrors.

**Comment by THPubs** [comment]
Is there a way to detect whether the url works or not and if it doesn't serve a different image hosted locally?

**Comment by redaxmedia** [comment]
There is a HTML only solution using a object tag with the unsplash-it url and a img tag inside with your fallback url.

**Comment by DMarby** [comment]
Super overdue late progress update on this, sorry about that.

Some slow progress has been made in terms of stabilizing the API with the increased load we're seeing (now serving roughly 400 million images a month) in the past few months, and those efforts are now continuing with a rewrite (can be found in the feature/rewrite repo of this branch).

We're currently re-architecting the service to sort out these issues once and for all, hoping to have the new codebase up and running within a few weeks.

**Comment by DMarby** [comment]
The rewrite of Picsum has now been completed, and deployed, so the stability issues should now be resolved. Hoping to do a write-up shortly detailing the new architecture. If you encounter any further problems, feel free to comment on this issue again, or poke me on twitter at @DMarby, and I'll look into it.
