### ISSUE TITLE
Allow CORS for consuming feed on client side 

### ISSUE THREAD

**Issue by MoOx** [DMarby/picsum-photos#2]
Recently I’ve create a simple project to make a replacement for new blank tab.
You can check it out here https://github.com/putaindecode/tab, or see it online here http://putaindecode.io/tab/
The code base is only JavaScript on the client side. So that would be great if CORS is allowed so I can consume the list feed with an XHR.

Are you open to allows CORS ?

**Comment by jovana** [comment]
Is it possible to also disable the CORS for this url: https://picsum.photos/id/0/info
I want to show a label to credit the author of the (random) photo we show.

Access to XMLHttpRequest at 'https://picsum.photos/id/284/info' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

(or will this only trigger on the localhost?)
