### ISSUE TITLE
Category support?

### ISSUE THREAD

**Issue by titos2k** [DMarby/picsum-photos#20]
i would love to have an option to get an image from specific category.

**Comment by benjaminb10** [comment]
Any news?

**Comment by DMarby** [comment]
Hi,
Currently we no plans to add category support. 
I would recommend checking out https://source.unsplash.com 
They allow you to get images based on search terms

**Comment by moacdev** [comment]
Use Unsplash Source for category-specific images:
-  Example for clothing:
  https://source.unsplash.com/300x300/?clothes
-  Example for electronics:
  https://source.unsplash.com/300x300/?electronics
