### ISSUE TITLE
EVERYTHING IS BROKED!

### ISSUE THREAD

**Issue by ACPixel** [DMarby/picsum-photos#23]
yup, title says it all, the site is _completely_ down. Well, all the images and stats are.

**Comment by JeremyIglehart** [comment]
This seams to be a recurring theme: #18 #22

If we could get some feedback on what the technical issues are from @DMarby we could help provide solutions.

**Comment by xcartmods** [comment]
down again :(

**Comment by diomed** [comment]
it's down again

**Comment by danbovey** [comment]
I have a [Chrome extension](http://github.com/danbovey/Tabbed.io) with a hundred or so users that uses unsplash.it, I'd be up for adding a donation link if that's something that would help with server costs etc.

**Comment by nijikokun** [comment]
Yeah, we should add a donation link to support server costs, it's running on a single instance right now so our cache fills quickly, when it is cleared the incoming requests are overloading the instance with I/O calls.

**Comment by danbovey** [comment]
Is there anything this API does that the new official API still doesn't do?

**Comment by nijikokun** [comment]
Not sure, haven't kept up with their feature set, you're free to use either one!

**Comment by DMarby** [comment]
Going to close this in favour of #18.
We're currently re-architecting the service to sort out these issues once and for all 👍
