### ISSUE TITLE
Request: adding a filename

### ISSUE THREAD

**Issue by jeffijoe** [DMarby/picsum-photos#31]
Example:

```
https://unsplash.it/200/300/randomname.png
```

**Comment by nijikokun** [comment]
Hey there :wave:

What functionality would the filename provide?

**Comment by jeffijoe** [comment]
Client-side, to determine what type of file you're dealing with, or displaying it - you know, for seed data purposes 😀

**Comment by nijikokun** [comment]
@DMarby thoughts?

**Comment by jeffijoe** [comment]
It would not affect the image itself, just for client side purposes

**Comment by jeffijoe** [comment]
Simple implementation (not tested but I imagine this would work):

```
  function setupRoutes (postfix) {
    app.get('/:size' + postfix, function (req, res, next) {
      serveImage(req, res, true, false)
    })

    app.get('/g/:size' + postfix, function (req, res, next) {
      serveImage(req, res, true, true)
    })

    app.get('/:width/:height' + postfix, function (req, res, next) {
      serveImage(req, res, false, false)
    })

    app.get('/g/:width/:height' + postfix, function (req, res, next) {
      serveImage(req, res, false, true)
    })
  }
  
  setupRoutes('')
  setupRoutes('/*')
```

**Comment by nijikokun** [comment]
Thanks for the code 🤘

Thinking more in terms of scope of whether it's something we want!

Something as simple as a conditional splat would work: `/:width/:height/*?`

**Comment by jeffijoe** [comment]
Yeah it wouldn't have to be required - sorry not that familiar with Express' router. 😄 

My use case is that I'm working on a file sharing app, where you can share images, videos and other files.

Based on the file name (which I extract from the download URL, which points Unsplash in development) I determine what type of icon to display, and I also display the filename itself.

**Comment by DMarby** [comment]
This sounds like a great idea, will try to bring this feature into the currently ongoing rewrite 👍

**Comment by mike-pt** [comment]
I bumped into this but I was looking for something else...

When we ask for say 2 random pic with same size we get the filename "size.jpg" in both cases... 

would it be possible to add the filename header, server-side:
```
Content-Disposition: attachment; filename="filename.jpg"
```

The filename would match whatever we redirect to now:
```bash
$http -h https://picsum.photos/600/400/?random |grep Loca
Location: /600/400/?image=214
$http -h https://picsum.photos/600/400/?random |grep Loca
Location: /600/400/?image=588
```

The idea behind this is that I want to generate random pics but I don't want copies of the same (which I can script if I have that filename)

**Comment by DMarby** [comment]
After further consideration I'm going to close this issue, I don't think it's worth the added complexity.
You can add `.jpg` to the end of an URL if you need a file extension, eg https://picsum.photos/300.jpg

**Comment by DMarby** [comment]
> I bumped into this but I was looking for something else...
> 
> When we ask for say 2 random pic with same size we get the filename "size.jpg" in both cases...
> 
> would it be possible to add the filename header, server-side:
> 
> ```
> Content-Disposition: attachment; filename="filename.jpg"
> ```
> The filename would match whatever we redirect to now:
> 
> ```shell
> $http -h https://picsum.photos/600/400/?random |grep Loca
> Location: /600/400/?image=214
> $http -h https://picsum.photos/600/400/?random |grep Loca
> Location: /600/400/?image=588
> ```
> 
> The idea behind this is that I want to generate random pics but I don't want copies of the same (which I can script if I have that filename)

Adding the content-disposition header would trigger the file to be downloaded, which is not desired for most cases in a browser, so that's not possible unfortunately.
If you want to ensure that you don't get duplicates, I would recommend using the `/v2/list` endpoint to get a list of images and then download them using the `/id` endpoint.
More information about how to use it can be found on the website under "List Images": https://picsum.photos/

**Comment by mike-pt** [comment]
A right @DMarby good cool, but it could be done as:
`Content-Disposition:  "inline; filename=name.extension"`

Filename is still passed and it doesn't force download (I copy pasted in the previous post and didn't realize I was suggesting `attachment`

**Comment by DMarby** [comment]
> A right @DMarby good cool, but it could be done as:
> `Content-Disposition: "inline; filename=name.extension"`
> 
> Filename is still passed and it doesn't force download (I copy pasted in the previous post and didn't noticed I was suggesting `attachment`)

Right, I didn't realize you could use filename with `inline`, neat!
I've added it to the service now, it might take some time to propagate for images that are already cached by our CDN, but it'll show up eventually.
