### ISSUE TITLE
how to crop gravity on specific image?

### ISSUE THREAD

**Issue by diomed** [DMarby/picsum-photos#32]
this doesn't seem to work (for me), or I'm missing something out.
I'm having trouble with cropping gravity when I select specific image.

Can you help me out a bit?

**Comment by alexanderkopke** [comment]
One can add the specific image using `&`
Example: `https://unsplash.it/200/300/?gravity=east&image=1054`

**Comment by DMarby** [comment]
Thanks for reaching out, sorry about the super slow reply, happy you got it working!
Going to clarify this on the main page since it's a question that shows up fairly commonly.

**Comment by DMarby** [comment]
Closing this as crop gravity is going away in the current rewrite of picsum.
