### ISSUE TITLE
/list endpoint reccomendation

### ISSUE THREAD

**Issue by josephmwells** [DMarby/picsum-photos#37]
I propose a change to the `/list` endpoint. The JSON Object returned from the API does not have any information regarding the image location. Either update the documentation for a correct usage of the JSON Object, or add a URL that can be parsed.

**Comment by DMarby** [comment]
Hi,

What do you mean by image location?

**Comment by DMarby** [comment]
Going to close this since I'm unsure what it means, feel free to clarify and I'll re-open it.
If you meant a way to get the full-sized image, `/v2/list` now has a field called `download_url` to allow this.
