### ISSUE TITLE
How to get tagged photos?

### ISSUE THREAD

**Issue by asimqt** [DMarby/picsum-photos#40]
Let's say I want to get the photos tagged with _food_, so that the images are related to my food application demo website. Is there an option for that?

**Comment by sushicodeur** [comment]
You can use unsplash directly : 

https://source.unsplash.com/random/1600x900?food

The full documentation is there : https://source.unsplash.com/

Plus, it seems that picsum doesn't follow the unsplash guidelines concerning [hotlinking](https://unsplash.com/documentation#hotlinking), this service may be taken down at some time if they don't fix this.

**Comment by DMarby** [comment]
Like @sushicodeur mentioned, you can use Unsplash Source directly if you want to get tagged images. Picsum doesn’t currently support this functionality, and we don’t plan to right now either.

As for hotlinking, Picsum doesn’t use the Unsplash API, so we have no reason to.
Picsum predates the Unsplash API, as well as the Unsplash license, all the images used in the service were gathered in the time when all Unsplash images was Creative Commons licensed.
