### ISSUE TITLE
Add way to get source information for an image.

### ISSUE THREAD

**Issue by Graham42** [DMarby/picsum-photos#42]
There's times when I get a particular image and I really like it and would like to find the unsplash source posting.

Can we add an endpoint like `/describe?image=0` that would give the same info as `/list` but just for that specific image?

It would also be cool to have the source image URL in the EXIF data of the image. A brief search turned up some thoughts on how to do this https://cweiske.de/tagebuch/exif-url.htm

**Comment by abhilash1in** [comment]
How about a header with source URL instead of a new endpoint? Avoids having to make multiple calls and is better in my opinion. I'm interested to work on this next week.

**Comment by DMarby** [comment]
This has now been implemented in the following way:
- All photos now contain Exif metadata, with the Picsum ID in the `UserComment` field (will take up to a month before caches clear for existing ones however)
- There's a new header called `Picsum-ID` which has the Picsum ID of the image
- There's a new API call available on `/id/{id}/info` that will return info about a single image.

Thanks to @abhilash1in for their work on the header/info endpoints.
