### ISSUE TITLE
Question. Self/local hosted instance?

### ISSUE THREAD

**Issue by evanre** [DMarby/picsum-photos#43]
Hi, thanks for awesome service! I'm using your service every day. But sometimes I have troubles with my internet connection and development process stops.

Is there a way to run this service on my local server? Thank you

**Comment by DMarby** [comment]
Hi,

I've added instructions for how to run a local instance, as well as how to set up your own on DigitalOcean's kubernetes, to the [README](https://github.com/DMarby/picsum-photos/blob/master/README.md)

Let me know if you have any more questions/issues with running your own instances, and I'll do my best to help
