### ISSUE TITLE
Can the image url's have the source images file extension like .jpg or .png.

### ISSUE THREAD

**Issue by Gabrieldaboss65** [DMarby/picsum-photos#45]

**Comment by erosenberg** [comment]
Having this same issue...

**Comment by DMarby** [comment]
Hi!

Just to clarify, you want to be able to do https://picsum.photos/200/200.png or similar?

**Comment by DMarby** [comment]
This feature has been implemented now:

You can add `.jpg` to the end of any URL, eg https://picsum.photos/300.jpg or https://picsum.photos/id/1/300/300.jpg
