### ISSUE TITLE
Add Unsplash category selector

### ISSUE THREAD

**Issue by kinnectus** [DMarby/picsum-photos#52]
Just found this most epic of sites and wondered if an Unsplash category filter could be added to only return photos from a specific category:

E.g. https://picsum.photos/200/300/?cat=textures-patterns

Use case: placeholder background where one doesn't want any object/person pictures to be returned, or only return pictures of people if one wants to demonstrate a person profile page.

**Comment by DMarby** [comment]
Hi!

We’re not planning to add this currently. I would recommend trying out https://source.unsplash.cok if you want categories

**Comment by broofa** [comment]
Quick followup to help connect the dots for anyone looking for profile picture photos, you can get profile photo-like URL from unsplash as follows:
```javascript
async function getRandomHeadshot(width, height) {
  const res = await fetch(`https://source.unsplash.com/${width}x${height}/?headshot`);
  return res.url;
}
```
