### ISSUE TITLE
Images gallery order is wrong

### ISSUE THREAD

**Issue by jeremymouzin** [DMarby/picsum-photos#54]
Hi, when browsing images gallery on [https://picsum.photos/images](https://picsum.photos/images), they're not ordered properly.

Instead of having pictures 0, 1, 2, 3 etc. it's 0, 1, 10, 100, 1000, 1001, 1002 ... 1009, 101, 1010, 1011...

It seems that the numbers are compared using a string type instead of a number type?

**Comment by DMarby** [comment]
Hi,

This is intended, ID's used to be numbers, but now they are strings and should be handled as such.
