### ISSUE TITLE
Random `HTTP2_PROTOCOL_ERROR 200` on every other request

### ISSUE THREAD

**Issue by pReya** [DMarby/picsum-photos#56]
I am requesting four Picsum pictures on my current page. Since a couple of weeks I'm getting random errors, when fetching the pictures. 3/4 pictures always work fine, but one picture gives an error on every other request or so. My browser (Chrome 78) console tells me:

`GET https://picsum.photos/id/1074/1280/720 net::ERR_HTTP2_PROTOCOL_ERROR 200`

Any idea where this might come from?

**Comment by DMarby** [comment]
Hi,
Sorry about the delay for responding to this, is this still happening? If so, let me know and I'll reopen this issue and look into it further.
