### ISSUE TITLE
Sugestion: Search based on filename/Description/Author 

### ISSUE THREAD

**Issue by FrozenBeard** [DMarby/picsum-photos#60]
I absolutely love picsum.photos, I use it for a random wallpaper on my start page I made.
But im looking to use this in some other projects now and wonderd if we could get context based images on a search term, either using the filename/Description/Author of the source, For example I can find images for ships: https://unsplash.com/s/photos/ship

**Comment by DMarby** [comment]
Hi!

We’re not planning to add this currently. I would recommend trying out https://source.unsplash.com if you want tags.
