### ISSUE TITLE
Some image id's do not exist is it not better to use a range of ids instead of random holes on the range?

### ISSUE THREAD

**Issue by fenchai23** [DMarby/picsum-photos#65]
as an example after playing the API on my app I discovered some empty ids:
https://picsum.photos/id/105/1440/2392/ as an example.

why not fill the empty ids?

I feel like this is a better approach than me working around the issue with backend.

thanks for the hard work

**Comment by DMarby** [comment]
We have no plans to fill any gaps in the IDs.
You can use the `/seed/{seed}/{width}/{height}` endpoint for consistent unique images, or the `/v2/list` to get a list of valid IDs. For more info see https://picsum.photos

In the future, please refrain from opening duplicate issues on already answered questions.
#59 #53 #25 #36 and so on.
