### ISSUE TITLE
A way to credit the image

### ISSUE THREAD

**Issue by mr-northwatch** [DMarby/picsum-photos#69]
Right now, I usually just say "Random image picked by Picsum from Unsplash", but I would like to be able to credit the photographer.

What if there was a ?credit=1 option where it could insert a dark-grey bar at the bottom of the image with a credit?

**Comment by DMarby** [comment]
Hi,

While this sounds like a potentially useful feature, this would add a lot of extra required processing/caching as it doubles the cache space of processed images.
Please note that you can look up information of any returned image by grabbing the ID from the `Picsum-ID` HTTP header and using the `/id/{id}/info` endpoint, more details on how to use it can be found at the bottom of https://picsum.photos
