### ISSUE TITLE
Sepia filter

### ISSUE THREAD

**Issue by CyberMew** [DMarby/picsum-photos#78]
This is really great, but besides grayscale is it possible to have sepia as well?

Also just wondering, I don't suppose the unsplash photos also come with categories right? Would be awesome if we could just get random photos for certain categories, e.g. buildings/nature/cats

**Comment by fcoterroba** [comment]
I can do it. @DMarby

**Comment by DMarby** [comment]
Hi,

We’re not planning to add this currently as any more variations of image processing require a lot more processing power/caching as the number of possible variations goes up.
