### ISSUE TITLE
Picsum not working: Error 503 Backend fetch failed

### ISSUE THREAD

**Issue by Zabrane** [DMarby/picsum-photos#80]
Hi @DMarby 

Since yesterday, we noticed that [large pictures](https://i.picsum.photos/id/536/1920/1000.png?hmac=Md5bzS1353tYTA_Gz1XTwzXs-6Civ2JeZyILYqkr_QI) are broken:
```
Error 503 Backend fetch failed

Backend fetch failed
Guru Meditation:
XID: 456179659
Varnish cache server
```

You can check by yourself, click the [Grayscale](https://picsum.photos/) link example.

**Comment by DMarby** [comment]
Hi,

Unfortunately DigitalOcean Spaces is having issues which is causing this, it will hopefully be resolved soon:
https://status.digitalocean.com/incidents/dw9913v02mq7

Regards,
