### ISSUE TITLE
Category Filter

### ISSUE THREAD

**Issue by danilosandoval** [DMarby/picsum-photos#81]
Hi Guys! Love this. Consider add category param to get a photo as a ?category=virtual-reality
Can I help?

**Comment by mholt** [comment]
Can you help us understand why this isn't planned? Would you accept a contribution?

**Comment by mholt** [comment]
Ohhh, that makes sense. Thanks for the background!

(My use case is a bunch of fake "persons" in a demo database, and needing profile pictures, which naturally should be of people.)

**Comment by matbrgz** [comment]
Noo problem, I can handle that. The unspash provide a category list, I can put this information in an array. Does it make sense? If it happens, you could implement this?

Print
![image](https://github.com/DMarby/picsum-photos/assets/23284276/2d02582e-ee59-4ac3-85b6-e6d7f10fdd35)

Array example
Image
https://unsplash.com/photos/man-in-front-of-laptop-computer-in-shallow-focus-photography-LNRyGwIJr5c


Image manifest
```
{
            "id": "1",
            "author": "Alejandro Escamilla",
            "width": 5000,
            "height": 3333,
            "url": "https://unsplash.com/photos/LNRyGwIJr5c"
            "category": ["Work","Blog","Working","Technology","Typing","Website Backgrounds","Business","Man","Hd Mac Wallpapers","Hd Macbook Wallpapers","Apple Images & Photos","Macbook Pro","Write","Desk","Office","Writing","Table","Coffee Images","Cell Phone","Clean","HD Wallpapers",],
},
```

This make sense?

**Comment by DMarby** [comment]
Hi @matbrgz, as mentioned in https://github.com/DMarby/picsum-photos/issues/81#issuecomment-1340068800 we can't use any data from Unsplash due to their licensing, so all images would need to be manually tagged without referencing Unsplash.

**Comment by kyoshino** [comment]
@DMarby Thank you for the great product! We have integrated Lorem Picsum with [Sveltia CMS](https://sveltiacms.app/en/), and our users seem to like it.

The lack of descriptions and categories has been noted in our [documentation](https://sveltiacms.app/en/docs/integrations/stock-photos), and I’m now considering to solve the issue by generating descriptions with Claude and providing them to our users, mainly for accessibility purposes.

However, it would be better if this were solved upstream. Do you accept <del>PR</del> generated data for this?
