### ISSUE TITLE
base64 content in the info

### ISSUE THREAD

**Issue by f1oppa** [DMarby/picsum-photos#87]
Add Base64 content to the https://picsum.photos/id/0/info/info

**Comment by DMarby** [comment]
Hi there, thank you for opening an issue.

Are you suggesting that we should base64 encode the image itself and add it to the info endpoint, or what are you asking?

**Comment by DMarby** [comment]
Thank you for your suggestion, this feature doesn't meet the goals for the project, so we will not be implementing this.
